#!/usr/bin/env fish
# Help text

function _wt_help
    echo "Worktree Toolkit (wt) - Git worktree management with Graphite integration"
    echo ""
    echo "Usage: wt <command> [options]"
    echo ""
    echo "Repository Management:"
    echo "  init <repo-url> [name]    Clone and set up worktree structure"
    echo "  clone <repo-url> [name]   Alias for init"
    echo ""
    echo "Worktree Operations:"
    echo "  new <name> [options]        Create new worktree (or checkout remote)"
    echo "    --from <base>             Base branch (default: trunk)"
    echo "    --force-new               Skip remote check, always create new"
    echo "    --switch                  Open in muxit after creation"
    echo "  list                        List all worktrees"
    echo "  switch <name>               Open worktree in muxit (no cd)"
    echo "  remove <name>               Remove worktree"
    echo ""
    echo "Stack Operations:"
    echo "  stack list                  Show all stacks"
    echo "  stack sync [name]           Sync entire stack"
    echo "  restack                     Rebase current stack"
    echo ""
    echo "Navigation:"
    echo "  up                          Switch to upstack worktree"
    echo "  down                        Switch to downstack worktree"
    echo "  bottom                      Switch to stack base"
    echo ""
    echo "Development:"
    echo "  status [--all]              Show worktree status"
    echo "  sync [--all] [--force]      Sync with remote"
    echo "  submit                      Submit stack to GitHub"
    echo ""
    echo "Environment:"
    echo "  env sync [--all]            Copy environment files"
    echo ""
    echo "Git Operations:"
    echo "  git <args>                  Run git commands in bare repository"
    echo ""
    echo "Other:"
    echo "  help                        Show this help"
    echo "  version                     Show version"
end