# Fish completion for mise
# This is a placeholder - actual completions will be generated by mise itself

# If you want to generate completions manually, run:
# mise completion fish > ~/.local/share/mise/completions/mise.fish

# For now, we'll use a basic completion
complete -c mise -f -a "activate use install ls ls-remote current uninstall upgrade plugin reshim env exec shell settings sync run tasks"