#!/usr/bin/env bash
#
# Run all dotfiles installers.

export current_user=jumski

set -e

cd "$(dirname $0)"/..

### Install pacman packages before everything
script/install_pacman_packages

### Run special installers first, so rest can depend on them
find . -name priority_install.sh | while read installer ; do sh -c "${installer}" ; done

### Run rest of installers
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# link everything
.dotbot/install
