#!/bin/bash

echo skipping becuz manjaro
exit 0

# find all repositories.apt so we can add new repositories and their keys before installing packages
find . -name repositories.apt -exec bash {} \;

# update in case we got some new repos
sudo apt update

# find all packages.apt so we can install dependencies before everything else
apt_packages=$(find . -name packages.apt -exec cat {} \; | tr '\n' ' ')
echo "Installing apt packages..."
sudo apt install -y $apt_packages
