#!/bin/bash

# find all packages.apt so we can install dependencies before everything else
apt_packages=$(find . -name packages.apt -exec cat {} \; | tr '\n' ' ')
echo "Installing apt packages..."
sudo apt install -y $apt_packages
