- link:
    ~/.config/fish/functions:
      path: fish/functions/*.fish
      glob: true
    ~/.config/fish/completions:
      path: fish/functions/*.fish
      glob: true
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/aliases.fish: fish/aliases.fish
    ~/.config/fish/fish_variables: fish/fish_variables
    ~/.config/fish/fishfile: fish/fishfile

- shell:
  - command: |
      fish -c \
      'if functions -q fisher
        fisher self-update
      else
        curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
      end'
    description: Installing/Updating Fisher
  - [fish -c fisher, Updating fish plugins]
