- link:
    ~/.config/fish/functions:
      path: fish/functions/*.fish
      glob: true
    ~/.config/fish/completions:
      path: fish/functions/*.fish
      glob: true
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/aliases.fish: fish/aliases.fish
    ~/.config/fish/fish_variables: fish/fish_variables
    ~/.config/fish/fishfile: fish/fishfile
