- link:
    ~/.logseq/preferences.json: /home/jumski/SynologyDrive/Areas/Dev/logseq-home-dir/preferences.json
    ~/.logseq/config: /home/jumski/SynologyDrive/Areas/Dev/logseq-home-dir/config
    ~/.logseq/plugins: /home/jumski/SynologyDrive/Areas/Dev/logseq-home-dir/plugins
    ~/.logseq/settings: /home/jumski/SynologyDrive/Areas/Dev/logseq-home-dir/settings
