- link:
    ~/.config/nvim/init.lua: nvim/init.lua
    ~/.config/nvim/lua: nvim/lua
    ~/.config/nvim/lazy-lock.json: nvim/lazy-lock.json
    ~/.config/nvim/queries: treesitter/queries
    ~/.editorconfig: nvim/editorconfig
